# Generated by Django 2.1.5 on 2019-02-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_attachments', '0003_auto_20190227_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetype',
            options={'ordering': ('code',)},
        ),
        migrations.RemoveField(
            model_name='filetype',
            name='order',
        ),
    ]
