# Generated by Django 5.2.1 on 2025-05-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unicef_attachments", "0008_attachment_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="filetype",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
    ]
