# Generated by Django 2.1.7 on 2019-04-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unicef_attachments', '0003_auto_20190227_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentFlatOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_link', models.URLField(blank=True, verbose_name='Object Link')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicef_attachments.Attachment')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='sample.Author')),
            ],
        ),
    ]
