name: Continuous Integration Workflow
on: [push]
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: python:latest
    services:
      postgres:
        image: postgres:9.5
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        django-version: [2.2, 3.0]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e "py${{ matrix.python-version }}-d${{ matrix.django-version }}" -- py.test tests -v
        env:
          DATABASE_HOST: postgres
          DATABASE_NAME: postgres
          DATABASE_PASSWORD: postgres
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: build/coverage/index.html
